name: flutter_test_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: "^3.0.0"
  firebase_auth: "^0.5.1"
  camera: "^0.1.1"
  path_provider: "^0.4.0"
  async_loader: "^0.1.1"
  http: "^0.11.3+16"
  firebase_storage: "^0.2.0"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/nomakeup.png
    - assets/images/nolip.png
    - assets/images/noeye.png
    - assets/images/lipeye.png
    - assets/icons/sorry.png
    - assets/icons/anger.png
    - assets/icons/contempt.png
    - assets/icons/disgust.png
    - assets/icons/fear.png
    - assets/icons/hapinness.png
    - assets/icons/neutral.png
    - assets/icons/sadness.png
    - assets/icons/surprised.png
    - assets/icons/female-sign.png
    - assets/icons/masculine.png
    - assets/icons/thinking.png
    - assets/icons/delete.png
    - assets/icons/send.png
    - assets/icons/album.png
    - assets/icons/profile.png
    - assets/icons/camera.png
    - assets/icons/facebook.svg
    - assets/icons/google.svg
    - assets/icons/facebook.png
    - assets/icons/google.png
    - assets/images/city.jpg
    - assets/images/obj.jpg
    - assets/videos/city.mp4
  fonts:
    - family: Sifonn
      fonts:
        - asset: assets/fonts/SIFONN_BASIC_OUTLINE.otf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
